---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-helm-app
  namespace: wego-system
spec:
  chart:
    spec:
      chart: ./hello-world
      sourceRef:
        kind: GitRepository
        name: my-helm-app
  install: {}
  interval: 5m0s

